
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("52fea235-18c8-49ac-90ff-7b467fffc35a")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("plwoModel", "FK_reviews_genres", "genres", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(plwoModel.genre), "reviews", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(plwoModel.review), True)>
<Assembly: EdmRelationshipAttribute("plwoModel", "FK_picture_PhotoAlbum", "PhotoAlbum", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(plwoModel.PhotoAlbum), "Picture", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(plwoModel.Picture), True)>

#End Region
Namespace plwoModel
    
    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class edoPLwrEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new edoPLwrEntities object using the connection string found in the 'edoPLwrEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=edoPLwrEntities", "edoPLwrEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new edoPLwrEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "edoPLwrEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new edoPLwrEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "edoPLwrEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property genres() As ObjectSet(Of genre)
            Get
                If (_genres Is Nothing) Then
                    _genres = MyBase.CreateObjectSet(Of genre)("genres")
                End If
                Return _genres
            End Get
        End Property
    
        Private _genres As ObjectSet(Of genre)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property reviews() As ObjectSet(Of review)
            Get
                If (_reviews Is Nothing) Then
                    _reviews = MyBase.CreateObjectSet(Of review)("reviews")
                End If
                Return _reviews
            End Get
        End Property
    
        Private _reviews As ObjectSet(Of review)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property PhotoAlbums() As ObjectSet(Of PhotoAlbum)
            Get
                If (_PhotoAlbums Is Nothing) Then
                    _PhotoAlbums = MyBase.CreateObjectSet(Of PhotoAlbum)("PhotoAlbums")
                End If
                Return _PhotoAlbums
            End Get
        End Property
    
        Private _PhotoAlbums As ObjectSet(Of PhotoAlbum)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Pictures() As ObjectSet(Of Picture)
            Get
                If (_Pictures Is Nothing) Then
                    _Pictures = MyBase.CreateObjectSet(Of Picture)("Pictures")
                End If
                Return _Pictures
            End Get
        End Property
    
        Private _Pictures As ObjectSet(Of Picture)

        #End Region
        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the genres EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddTogenres(ByVal genre As genre)
            MyBase.AddObject("genres", genre)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the reviews EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToreviews(ByVal review As review)
            MyBase.AddObject("reviews", review)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the PhotoAlbums EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToPhotoAlbums(ByVal photoAlbum As PhotoAlbum)
            MyBase.AddObject("PhotoAlbums", photoAlbum)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Pictures EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToPictures(ByVal picture As Picture)
            MyBase.AddObject("Pictures", picture)
        End Sub

        #End Region
    End Class

    #End Region
    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="plwoModel", Name:="genre")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class genre
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new genre object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="name">Initial value of the name property.</param>
        ''' <param name="sorder">Initial value of the Sorder property.</param>
        Public Shared Function Creategenre(id As Global.System.Int32, name As Global.System.String, sorder As Global.System.Int32) As genre
            Dim genre as genre = New genre
            genre.Id = id
            genre.name = name
            genre.Sorder = sorder
            Return genre
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property name() As Global.System.String
            Get
                Return _name
            End Get
            Set
                OnnameChanging(value)
                ReportPropertyChanging("name")
                _name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("name")
                OnnameChanged()
            End Set
        End Property
    
        Private _name As Global.System.String
        Private Partial Sub OnnameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Sorder() As Global.System.Int32
            Get
                Return _Sorder
            End Get
            Set
                OnSorderChanging(value)
                ReportPropertyChanging("Sorder")
                _Sorder = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Sorder")
                OnSorderChanged()
            End Set
        End Property
    
        Private _Sorder As Global.System.Int32
        Private Partial Sub OnSorderChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnSorderChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("plwoModel", "FK_reviews_genres", "reviews")>
         Public Property reviews() As EntityCollection(Of review)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of review)("plwoModel.FK_reviews_genres", "reviews")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of review)("plwoModel.FK_reviews_genres", "reviews", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="plwoModel", Name:="PhotoAlbum")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class PhotoAlbum
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new PhotoAlbum object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="name">Initial value of the Name property.</param>
        Public Shared Function CreatePhotoAlbum(id As Global.System.Int32, name As Global.System.String) As PhotoAlbum
            Dim photoAlbum as PhotoAlbum = New PhotoAlbum
            photoAlbum.Id = id
            photoAlbum.Name = name
            Return photoAlbum
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Name() As Global.System.String
            Get
                Return _Name
            End Get
            Set
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Name")
                OnNameChanged()
            End Set
        End Property
    
        Private _Name As Global.System.String
        Private Partial Sub OnNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNameChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("plwoModel", "FK_picture_PhotoAlbum", "Picture")>
         Public Property Pictures() As EntityCollection(Of Picture)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Picture)("plwoModel.FK_picture_PhotoAlbum", "Picture")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Picture)("plwoModel.FK_picture_PhotoAlbum", "Picture", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="plwoModel", Name:="Picture")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Picture
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Picture object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="description">Initial value of the Description property.</param>
        ''' <param name="toolTip">Initial value of the ToolTip property.</param>
        ''' <param name="imageUrl">Initial value of the ImageUrl property.</param>
        ''' <param name="photoAlbumId">Initial value of the PhotoAlbumId property.</param>
        Public Shared Function CreatePicture(id As Global.System.Int32, description As Global.System.String, toolTip As Global.System.String, imageUrl As Global.System.String, photoAlbumId As Global.System.Int32) As Picture
            Dim picture as Picture = New Picture
            picture.Id = id
            picture.Description = description
            picture.ToolTip = toolTip
            picture.ImageUrl = imageUrl
            picture.PhotoAlbumId = photoAlbumId
            Return picture
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Description() As Global.System.String
            Get
                Return _Description
            End Get
            Set
                OnDescriptionChanging(value)
                ReportPropertyChanging("Description")
                _Description = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Description")
                OnDescriptionChanged()
            End Set
        End Property
    
        Private _Description As Global.System.String
        Private Partial Sub OnDescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDescriptionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ToolTip() As Global.System.String
            Get
                Return _ToolTip
            End Get
            Set
                OnToolTipChanging(value)
                ReportPropertyChanging("ToolTip")
                _ToolTip = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ToolTip")
                OnToolTipChanged()
            End Set
        End Property
    
        Private _ToolTip As Global.System.String
        Private Partial Sub OnToolTipChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnToolTipChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ImageUrl() As Global.System.String
            Get
                Return _ImageUrl
            End Get
            Set
                OnImageUrlChanging(value)
                ReportPropertyChanging("ImageUrl")
                _ImageUrl = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ImageUrl")
                OnImageUrlChanged()
            End Set
        End Property
    
        Private _ImageUrl As Global.System.String
        Private Partial Sub OnImageUrlChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnImageUrlChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property PhotoAlbumId() As Global.System.Int32
            Get
                Return _PhotoAlbumId
            End Get
            Set
                OnPhotoAlbumIdChanging(value)
                ReportPropertyChanging("PhotoAlbumId")
                _PhotoAlbumId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("PhotoAlbumId")
                OnPhotoAlbumIdChanged()
            End Set
        End Property
    
        Private _PhotoAlbumId As Global.System.Int32
        Private Partial Sub OnPhotoAlbumIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnPhotoAlbumIdChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("plwoModel", "FK_picture_PhotoAlbum", "PhotoAlbum")>
        Public Property PhotoAlbum() As PhotoAlbum
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of PhotoAlbum)("plwoModel.FK_picture_PhotoAlbum", "PhotoAlbum").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of PhotoAlbum)("plwoModel.FK_picture_PhotoAlbum", "PhotoAlbum").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property PhotoAlbumReference() As EntityReference(Of PhotoAlbum)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of PhotoAlbum)("plwoModel.FK_picture_PhotoAlbum", "PhotoAlbum")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of PhotoAlbum)("plwoModel.FK_picture_PhotoAlbum", "PhotoAlbum", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="plwoModel", Name:="review")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class review
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new review object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="title">Initial value of the title property.</param>
        ''' <param name="summary">Initial value of the summary property.</param>
        ''' <param name="genreId">Initial value of the genreId property.</param>
        ''' <param name="authorized">Initial value of the authorized property.</param>
        ''' <param name="createDateTime">Initial value of the createDateTime property.</param>
        ''' <param name="updateDateTime">Initial value of the updateDateTime property.</param>
        Public Shared Function Createreview(id As Global.System.Int32, title As Global.System.String, summary As Global.System.String, genreId As Global.System.Int32, authorized As Global.System.Boolean, createDateTime As Global.System.DateTime, updateDateTime As Global.System.DateTime) As review
            Dim review as review = New review
            review.Id = id
            review.title = title
            review.summary = summary
            review.genreId = genreId
            review.authorized = authorized
            review.createDateTime = createDateTime
            review.updateDateTime = updateDateTime
            Return review
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Int32
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Int32
        Private Partial Sub OnIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property title() As Global.System.String
            Get
                Return _title
            End Get
            Set
                OntitleChanging(value)
                ReportPropertyChanging("title")
                _title = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("title")
                OntitleChanged()
            End Set
        End Property
    
        Private _title As Global.System.String
        Private Partial Sub OntitleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OntitleChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property summary() As Global.System.String
            Get
                Return _summary
            End Get
            Set
                OnsummaryChanging(value)
                ReportPropertyChanging("summary")
                _summary = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("summary")
                OnsummaryChanged()
            End Set
        End Property
    
        Private _summary As Global.System.String
        Private Partial Sub OnsummaryChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnsummaryChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property body() As Global.System.String
            Get
                Return _body
            End Get
            Set
                OnbodyChanging(value)
                ReportPropertyChanging("body")
                _body = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("body")
                OnbodyChanged()
            End Set
        End Property
    
        Private _body As Global.System.String
        Private Partial Sub OnbodyChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnbodyChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property genreId() As Global.System.Int32
            Get
                Return _genreId
            End Get
            Set
                OngenreIdChanging(value)
                ReportPropertyChanging("genreId")
                _genreId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("genreId")
                OngenreIdChanged()
            End Set
        End Property
    
        Private _genreId As Global.System.Int32
        Private Partial Sub OngenreIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OngenreIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property authorized() As Global.System.Boolean
            Get
                Return _authorized
            End Get
            Set
                OnauthorizedChanging(value)
                ReportPropertyChanging("authorized")
                _authorized = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("authorized")
                OnauthorizedChanged()
            End Set
        End Property
    
        Private _authorized As Global.System.Boolean
        Private Partial Sub OnauthorizedChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnauthorizedChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property createDateTime() As Global.System.DateTime
            Get
                Return _createDateTime
            End Get
            Set
                OncreateDateTimeChanging(value)
                ReportPropertyChanging("createDateTime")
                _createDateTime = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("createDateTime")
                OncreateDateTimeChanged()
            End Set
        End Property
    
        Private _createDateTime As Global.System.DateTime
        Private Partial Sub OncreateDateTimeChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OncreateDateTimeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property updateDateTime() As Global.System.DateTime
            Get
                Return _updateDateTime
            End Get
            Set
                OnupdateDateTimeChanging(value)
                ReportPropertyChanging("updateDateTime")
                _updateDateTime = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("updateDateTime")
                OnupdateDateTimeChanged()
            End Set
        End Property
    
        Private _updateDateTime As Global.System.DateTime
        Private Partial Sub OnupdateDateTimeChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnupdateDateTimeChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("plwoModel", "FK_reviews_genres", "genres")>
        Public Property genre() As genre
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of genre)("plwoModel.FK_reviews_genres", "genres").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of genre)("plwoModel.FK_reviews_genres", "genres").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property genreReference() As EntityReference(Of genre)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of genre)("plwoModel.FK_reviews_genres", "genres")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of genre)("plwoModel.FK_reviews_genres", "genres", value)
                End If
            End Set
        End Property

        #End Region
    End Class

    #End Region
    
End Namespace
